_BASE_: "../../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  # WEIGHTS: "/netapp/l.lemikhova/projects/VOS/vos/detection/data/configs/Fruits-Detection/faster-rcnn/vanilla_from_scratch/random_seed_0/model_final.pth"

  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 80

INPUT:
  # MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN: (480, )
  MAX_SIZE_TRAIN: 480
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 480
DATASETS:
  TRAIN: ('coco_2017_train',)
  TEST: ('coco_2017_val',)
