# CUDA_VISIBLE_DEVICES=2,3 python vos/detection/train_net.py --num-gpus 1 --config-file Fruits-Detection/Faster-RCNN/coco_openim/vanilla_from_scratch_7.yaml --random-seed 1 --resume
_BASE_: "../../../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  # WEIGHTS: "/netapp/l.lemikhova/projects/VOS_forked/vos/detection/data/Faster-RCNN/coco_openim/vanilla_from_scratch_7/random_seed_0/model_final.pth"

  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 7
INPUT:
  MIN_SIZE_TRAIN: (640, )  # (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 640  # 640
  MIN_SIZE_TEST: 640  # 800
  MAX_SIZE_TEST: 640  # 800
DATASETS:
  TRAIN: ('coco_ext_fruits_train', 'openim_id_fruits_train')
  # TEST: ('openim_id_fruits_val', )
  TEST: ('deep_fruits_id_fruits_test', )
  # TEST: ('openim_id_fruits_val', 'coco_ext_fruits_val')
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02  # 0.02
  STEPS: (6000, 8000)
  MAX_ITER: 9000  # 17.4 epochs
  # MAX_ITER: 200  # 17.4 epochs
  WARMUP_ITERS: 1000  # 100
  CHECKPOINT_PERIOD: 1000
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory, 8
TEST:
  EVAL_PERIOD: 500  # 500